services:
  rabbitmq:
    image: rabbitmq:3.13-management
    platform: linux/amd64
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brightertests
