services:
  rabbitmq:
    image: rabbitmq:3.13-management
    platform: linux/amd64
    ports:
      - "5672:5672"
      - "15672:15672"
  sqlserver:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=brighter_test
      - MYSQL_ROOT_PASSWORD=Password123!
